import { DefinitionSchema } from './DefinitionGenerator'

const appSystemEvents: DefinitionSchema = {
  tableName: 'AppSystemEvents',
  columns: [
    { name: '_ResourceGUID', type: 'string' },
    { name: 'AppVersion', type: 'string' },
    { name: '_ResourceId', type: 'string' },
    { name: 'Assembly', type: 'string' },
    { name: 'ClientBrowser', type: 'string' },
    { name: 'ClientCity', type: 'string' },
    { name: 'ClientCountryOrRegion', type: 'string' },
    { name: 'ClientIP', type: 'string' },
    { name: 'ClientModel', type: 'string' },
    { name: 'ClientOS', type: 'string' },
    { name: 'ClientStateOrProvince', type: 'string' },
    { name: 'ClientType', type: 'string' },
    { name: 'AppRoleInstance', type: 'string' },
    { name: 'AppRoleName', type: 'string' },
    { name: 'Properties', type: 'dynamic' },
    { name: 'Measurements', type: 'dynamic' },
    { name: 'Details', type: 'dynamic' },
    { name: 'HandledAt', type: 'string' },
    { name: 'IKey', type: 'string' },
    { name: 'InnermostAssembly', type: 'string' },
    { name: 'InnermostMessage', type: 'string' },
    { name: 'InnermostMethod', type: 'string' },
    { name: 'InnermostType', type: 'string' },
    { name: 'ItemCount', type: 'int' },
    { name: '_ItemId', type: 'string' },
    { name: 'Type', type: 'string' },
    { name: 'Message', type: 'string' },
    { name: 'Method', type: 'string' },
    { name: 'OperationId', type: 'string' },
    { name: 'OperationName', type: 'string' },
    { name: 'OperationParentId', type: 'string' },
    { name: 'OperationSyntheticSource', type: 'string' },
    { name: 'OuterAssembly', type: 'string' },
    { name: 'OuterMessage', type: 'string' },
    { name: 'OuterMethod', type: 'string' },
    { name: 'OuterType', type: 'string' },
    { name: 'ProblemId', type: 'string' },
    { name: 'SdkVersion', type: 'string' },
    { name: 'SessionId', type: 'string' },
    { name: 'SeverityLevel', type: 'int' },
    { name: 'TimeGenerated', type: 'datetime' },
    { name: 'ExceptionType', type: 'string' },
    { name: 'UserAccountId', type: 'string' },
    { name: 'UserAuthenticatedId', type: 'string' },
    { name: 'UserId', type: 'string' },
  ],
}

const appDependencies: DefinitionSchema = {
  tableName: 'AppDependencies',
  columns: [
    { name: '_ResourceGUID', type: 'string' },
    { name: 'AppVersion', type: 'string' },
    { name: '_ResourceId', type: 'string' },
    { name: 'ClientBrowser', type: 'string' },
    { name: 'ClientCity', type: 'string' },
    { name: 'ClientCountryOrRegion', type: 'string' },
    { name: 'ClientIP', type: 'string' },
    { name: 'ClientModel', type: 'string' },
    { name: 'ClientOS', type: 'string' },
    { name: 'ClientStateOrProvince', type: 'string' },
    { name: 'ClientType', type: 'string' },
    { name: 'AppRoleInstance', type: 'string' },
    { name: 'AppRoleName', type: 'string' },
    { name: 'Properties', type: 'dynamic' },
    { name: 'Measurements', type: 'dynamic' },
    { name: 'Data', type: 'string' },
    { name: 'DurationMs', type: 'real' },
    { name: 'Id', type: 'string' },
    { name: 'IKey', type: 'string' },
    { name: 'ItemCount', type: 'int' },
    { name: '_ItemId', type: 'string' },
    { name: 'Type', type: 'string' },
    { name: 'Name', type: 'string' },
    { name: 'OperationId', type: 'string' },
    { name: 'OperationName', type: 'string' },
    { name: 'OperationParentId', type: 'string' },
    { name: 'OperationSyntheticSource', type: 'string' },
    { name: 'PerformanceBucket', type: 'string' },
    { name: 'ResultCode', type: 'string' },
    { name: 'SdkVersion', type: 'string' },
    { name: 'SessionId', type: 'string' },
    { name: 'Success', type: 'bool' },
    { name: 'Target', type: 'string' },
    { name: 'TimeGenerated', type: 'datetime' },
    { name: 'DependencyType', type: 'string' },
    { name: 'UserAccountId', type: 'string' },
    { name: 'UserAuthenticatedId', type: 'string' },
    { name: 'UserId', type: 'string' },
  ],
}

const appMetrics: DefinitionSchema = {
  tableName: 'AppMetrics',
  columns: [
    { name: '_ResourceGUID', type: 'string' },
    { name: 'AppVersion', type: 'string' },
    { name: '_ResourceId', type: 'string' },
    { name: 'ClientBrowser', type: 'string' },
    { name: 'ClientCity', type: 'string' },
    { name: 'ClientCountryOrRegion', type: 'string' },
    { name: 'ClientIP', type: 'string' },
    { name: 'ClientModel', type: 'string' },
    { name: 'ClientOS', type: 'string' },
    { name: 'ClientStateOrProvince', type: 'string' },
    { name: 'ClientType', type: 'string' },
    { name: 'AppRoleInstance', type: 'string' },
    { name: 'AppRoleName', type: 'string' },
    { name: 'Properties', type: 'dynamic' },
    { name: 'IKey', type: 'string' },
    { name: '_ItemId', type: 'string' },
    { name: 'Type', type: 'string' },
    { name: 'Name', type: 'string' },
    { name: 'OperationId', type: 'string' },
    { name: 'OperationName', type: 'string' },
    { name: 'OperationParentId', type: 'string' },
    { name: 'OperationSyntheticSource', type: 'string' },
    { name: 'SdkVersion', type: 'string' },
    { name: 'SessionId', type: 'string' },
    { name: 'TimeGenerated', type: 'datetime' },
    { name: 'UserAccountId', type: 'string' },
    { name: 'UserAuthenticatedId', type: 'string' },
    { name: 'UserId', type: 'string' },
    { name: 'ValueCount', type: 'int' },
    { name: 'ValueMax', type: 'real' },
    { name: 'ValueMin', type: 'real' },
    { name: 'ValueStdDev', type: 'real' },
    { name: 'ValueSum', type: 'real' },
  ],
}

const appRequests: DefinitionSchema = {
  tableName: 'AppRequests',
  columns: [
    { name: '_ResourceGUID', type: 'string' },
    { name: 'AppVersion', type: 'string' },
    { name: '_ResourceId', type: 'string' },
    { name: 'ClientBrowser', type: 'string' },
    { name: 'ClientCity', type: 'string' },
    { name: 'ClientCountryOrRegion', type: 'string' },
    { name: 'ClientIP', type: 'string' },
    { name: 'ClientModel', type: 'string' },
    { name: 'ClientOS', type: 'string' },
    { name: 'ClientStateOrProvince', type: 'string' },
    { name: 'ClientType', type: 'string' },
    { name: 'AppRoleInstance', type: 'string' },
    { name: 'AppRoleName', type: 'string' },
    { name: 'Properties', type: 'dynamic' },
    { name: 'Measurements', type: 'dynamic' },
    { name: 'DurationMs', type: 'real' },
    { name: 'Id', type: 'string' },
    { name: 'IKey', type: 'string' },
    { name: 'ItemCount', type: 'int' },
    { name: '_ItemId', type: 'string' },
    { name: 'Type', type: 'string' },
    { name: 'Name', type: 'string' },
    { name: 'OperationId', type: 'string' },
    { name: 'OperationName', type: 'string' },
    { name: 'OperationParentId', type: 'string' },
    { name: 'OperationSyntheticSource', type: 'string' },
    { name: 'PerformanceBucket', type: 'string' },
    { name: 'ResultCode', type: 'string' },
    { name: 'SdkVersion', type: 'string' },
    { name: 'SessionId', type: 'string' },
    { name: 'Source', type: 'string' },
    { name: 'Success', type: 'bool' },
    { name: 'TimeGenerated', type: 'datetime' },
    { name: 'Url', type: 'string' },
    { name: 'UserAccountId', type: 'string' },
    { name: 'UserAuthenticatedId', type: 'string' },
    { name: 'UserId', type: 'string' },
  ],
}

const appTraces: DefinitionSchema = {
  tableName: 'AppTraces',
  columns: [
    { name: '_ResourceGUID', type: 'string' },
    { name: 'AppVersion', type: 'string' },
    { name: '_ResourceId', type: 'string' },
    { name: 'ClientBrowser', type: 'string' },
    { name: 'ClientCity', type: 'string' },
    { name: 'ClientCountryOrRegion', type: 'string' },
    { name: 'ClientIP', type: 'string' },
    { name: 'ClientModel', type: 'string' },
    { name: 'ClientOS', type: 'string' },
    { name: 'ClientStateOrProvince', type: 'string' },
    { name: 'ClientType', type: 'string' },
    { name: 'AppRoleInstance', type: 'string' },
    { name: 'AppRoleName', type: 'string' },
    { name: 'Properties', type: 'dynamic' },
    { name: 'Measurements', type: 'dynamic' },
    { name: 'IKey', type: 'string' },
    { name: 'ItemCount', type: 'int' },
    { name: '_ItemId', type: 'string' },
    { name: 'Type', type: 'string' },
    { name: 'Message', type: 'string' },
    { name: 'OperationId', type: 'string' },
    { name: 'OperationName', type: 'string' },
    { name: 'OperationParentId', type: 'string' },
    { name: 'OperationSyntheticSource', type: 'string' },
    { name: 'SdkVersion', type: 'string' },
    { name: 'SessionId', type: 'string' },
    { name: 'SeverityLevel', type: 'int' },
    { name: 'TimeGenerated', type: 'datetime' },
    { name: 'UserAccountId', type: 'string' },
    { name: 'UserAuthenticatedId', type: 'string' },
    { name: 'UserId', type: 'string' },
  ],
}

export { appSystemEvents, appDependencies, appMetrics, appRequests, appTraces }
